### ISSUE TITLE
Issue about slot

### ISSUE THREAD

**Issue by oyexiaozhi** [HcySunYang/vuese#72] opened 2019-04-29 06:10 UTC
**Describe the bug**
<template>
  <div>
    <template #searchSlot>
      
      <slot name="searchSlot"></slot>
    </template>
  </div>
</template>

**Expected behavior**
render out the slot in markdown file

**Which version do you use:**
"@vuese/markdown-render": "^2.2.7"
"@vuese/parser": "^2.1.6"

**Comment by oyexiaozhi** [comment] 2019-04-29 06:11
**Describe the bug**
<template>
  <div>
    <template #searchSlot>
      
      <slot name="searchSlot"></slot>
    </template>
  </div>
</template>

**Comment by oyexiaozhi** [comment] 2019-04-29 06:11
"<template>
  <div>
    <template #searchSlot>
      
      <slot name="searchSlot"></slot>
    </template>
  </div>
</template>"

**Comment by oyexiaozhi** [comment] 2019-04-29 06:13
```html
<template>
  <div>
    <template #searchSlot>
      <!-- search slot -->
      <slot name="searchSlot"></slot>
    </template>
  </div>
</template>
```

**Comment by MisicDemone** [comment] 2019-12-17 11:04
same issue🤕

**Comment by IWANABETHATGUY** [comment] 2020-04-26 05:39
Duplicate of #119

**Comment by IWANABETHATGUY** [comment] 2020-04-27 05:55
will be fixed by #161

**Closed as completed** 2020-04-27 05:56 UTC
Labels: bug, duplicate
