### ISSUE TITLE
.sync event are generated in documentation

### ISSUE THREAD

**Issue by devcashsrl** [HcySunYang/vuese#135] opened 2020-04-01 11:51 UTC
**Describe the bug**
@vuese/cli documentation in "Writing documentation for your component -> events -> .sync event" explain that events named "upadate:xxx" will not be included in the generated documentation, but is not so.

**Expected behavior**
I expect that the these type of events will not be included in the generated documentation.

**Environmental information:**
vuese v2.8.3.

**Comment by IWANABETHATGUY** [comment] 2020-04-14 05:27
Duplicate of #116

**Comment by IWANABETHATGUY** [comment] 2020-04-14 13:59
will fix by #144

**Closed as completed** 2020-04-16 03:35 UTC
